---
title: "Arthur Boari"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
      smooth_scroll: true
---
<style>
body {
  color: black;
  font-family: Times;
  font-size: 20px;
}
pre {
  background-color: lightgreen;
}
#TOC {
  color: #A8CF45;
  font-family: Times;
  font-size: 14px;
  border-color: black;
}
#header {
  color: #00943E;
  align: center;
}
</style>

<br>
<br>

# National Conferences

## 19º Congresso Nacional de Meio Ambiente de Poços de Caldas

Conference dates: 2022/09/20-22

Place: Poços de Caldas, Minas Gerais, Brazil.

Full paper: <a href="Arquivos/Publicacoes/Resumo identificado final.pdf" >submitted version</a> or <a href="http://www.meioambientepocos.com.br/ANAIS2022/76%20-%20244016_crescimento-da-concentrao-de-materiais-particulados-e-oznio-em-capitais-brasileiras.pdf" >conference proceedings</a>.

Conference Proceedings: <a href="http://www.meioambientepocos.com.br/anais2022.html" >link here</a>.

Poster: <a href="Arquivos/Publicacoes/Banner.pptx (1).pdf" >pdf file</a>. 

References: [available here](https://arthurboari.github.io/arthurboari/cnmaref.html).

Website: [link](http://www.meioambientepocos.com.br/index.html) as accessed in 2022/09/19.

# Local Conferences

## XXXI Congresso da Pós-Graduação

Conference dates: 2022/11/03-04

Place: Universidade Federal de Lavras (Lavras, Minas Gerais, Brazil).

Full paper: <a href="Arquivos/Publicacoes/xxxi cpg/CPG2022_paper_138.pdf" >submitted version</a>.

Presentation: <a href="Arquivos/Publicacoes/xxxi cpg/Slides CPG 2022.pdf" >pdf file</a>. 

References: [available here](https://arthurboari.github.io/arthurboari/xxxicpg.html).

Website: [link](https://congressos.ufla.br/xxxicppg) as accessed in 2022/10/29.


&copy; 2022 Arthur Boari. All rights reserved.