# Build Stage: latex compilation
building-latex-master:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  stage: build
  image: cgaultier/ubuntu19.10:texlive-2019
  script:
    # latexmk compiles all .tex files in the directory
    - latexmk
  artifacts:
    # Keeps only the .pdf files
    paths:
      - "*.pdf"

# Deploy stage makes the artifacts available in the public folder of the repository
pages:
  stage: deploy
  script:
    - mkdir public  # creates a folder called public
    - cp *.pdf public  # copy the .pdf files into the public folder
  artifacts:
    paths:
      - public  # instructs GitLab to keep the public folder
  only:
    - master  # deploy the .pdf only for commits pushed to the master branch
